name: learn-github-actions
on: [push]

env:
  DAY_OF_WEEK: 4

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DAY_OF_WEEK && ('1'+env.DAY_OF_WEEK) || '' }}
      - run: npm install -g bats
      - run: bats -v
